-- Importação dos 137 produtos do arquivo Pasta1.csv
-- Rode este script INTEIRO no SQL Editor do Supabase.
-- (Não use o importador de CSV do Table Editor: o arquivo tem separador ";",
--  coluna id vazia e acentuação em latin-1, que é o que estava causando o erro.)

-- 1) Libera a categoria "paleta" no banco (o CHECK antigo não aceitava)
alter table produtos drop constraint if exists produtos_categoria_check;
alter table produtos add constraint produtos_categoria_check
  check (categoria in ('sorvete', 'picole', 'acai', 'monte_do_jeito', 'paleta'));

-- 2) Insere os produtos (o id é gerado automaticamente pelo banco)
insert into produtos (categoria, subcategoria, nome, preco, ativo) values
  ('picole', 'tradicional', 'Abacate', 9.9, true),
  ('picole', 'tradicional', 'Abacaxi ao Leite', 9.9, true),
  ('picole', 'tradicional', 'Abacaxi Fruta', 9.9, true),
  ('picole', 'tradicional', 'Acai', 9.9, true),
  ('picole', 'tradicional', 'Amendoim', 9.9, true),
  ('picole', 'tradicional', 'Amora', 9.9, true),
  ('picole', 'tradicional', 'Araticum', 9.9, true),
  ('picole', 'tradicional', 'Banana', 9.9, true),
  ('picole', 'tradicional', 'Buriti', 9.9, true),
  ('picole', 'tradicional', 'Cagaita', 9.9, true),
  ('picole', 'tradicional', 'Caja-Manga', 9.9, true),
  ('picole', 'tradicional', 'Cajuzinho do Cerrado', 9.9, true),
  ('picole', 'tradicional', 'Castanha de Caju', 9.9, true),
  ('picole', 'tradicional', 'Castanha do Para', 9.9, true),
  ('picole', 'tradicional', 'Chocolate', 9.9, true),
  ('picole', 'tradicional', 'Ciriguela', 9.9, true),
  ('picole', 'tradicional', 'Coalhada', 9.9, true),
  ('picole', 'tradicional', 'Coco Branco', 9.9, true),
  ('picole', 'tradicional', 'Coco Queimado', 9.9, true),
  ('picole', 'tradicional', 'Cupuacu', 9.9, true),
  ('picole', 'tradicional', 'Flocos', 9.9, true),
  ('picole', 'tradicional', 'Goiaba', 9.9, true),
  ('picole', 'tradicional', 'Graviola', 9.9, true),
  ('picole', 'tradicional', 'Groselha', 9.9, true),
  ('picole', 'tradicional', 'Jabuticaba', 9.9, true),
  ('picole', 'tradicional', 'Jaca', 9.9, true),
  ('picole', 'tradicional', 'Kiwi', 9.9, true),
  ('picole', 'tradicional', 'Leite Condensado', 9.9, true),
  ('picole', 'tradicional', 'Lichia', 9.9, true),
  ('picole', 'tradicional', 'Limao Fruta', 9.9, true),
  ('picole', 'tradicional', 'Limao Suico', 9.9, true),
  ('picole', 'tradicional', 'Mamao', 9.9, true),
  ('picole', 'tradicional', 'Manga', 9.9, true),
  ('picole', 'tradicional', 'Mangaba', 9.9, true),
  ('picole', 'tradicional', 'Maracuja ao Leite', 9.9, true),
  ('picole', 'tradicional', 'Maracuja Fruta', 9.9, true),
  ('picole', 'tradicional', 'Melancia', 9.9, true),
  ('picole', 'tradicional', 'Melao', 9.9, true),
  ('picole', 'tradicional', 'Milho Verde', 9.9, true),
  ('picole', 'tradicional', 'Morango ao Leite', 9.9, true),
  ('picole', 'tradicional', 'Morango Fruta', 9.9, true),
  ('picole', 'tradicional', 'Murici', 9.9, true),
  ('picole', 'tradicional', 'Olho de Sogra', 9.9, true),
  ('picole', 'tradicional', 'Pequi', 9.9, true),
  ('picole', 'tradicional', 'Romeu e Julieta', 9.9, true),
  ('picole', 'tradicional', 'Tamarindo', 9.9, true),
  ('picole', 'tradicional', 'Tapereba (Cajazinho)', 9.9, true),
  ('picole', 'tradicional', 'Tapioca', 9.9, true),
  ('picole', 'tradicional', 'Umbu', 9.9, true),
  ('picole', 'tradicional', 'Uva', 9.9, true),
  ('picole', 'premium', 'Acai com Cupuacu', 12.9, true),
  ('picole', 'premium', 'Acai com Ninho', 12.9, true),
  ('picole', 'premium', 'Acai com Tapioca', 12.9, true),
  ('picole', 'premium', 'Alfajor', 12.9, true),
  ('picole', 'premium', 'Avela com Chocolate', 12.9, true),
  ('picole', 'premium', 'Bacuri', 12.9, true),
  ('picole', 'premium', 'Baru', 12.9, true),
  ('picole', 'premium', 'Brigadeiro', 12.9, true),
  ('picole', 'premium', 'Chocolate Branco', 12.9, true),
  ('picole', 'premium', 'Chocomenta', 12.9, true),
  ('picole', 'premium', 'Coco Verde', 12.9, true),
  ('picole', 'premium', 'Doce de Leite', 12.9, true),
  ('picole', 'premium', 'Frutas do Bosque', 12.9, true),
  ('picole', 'premium', 'Maltine', 12.9, true),
  ('picole', 'premium', 'Ninho', 12.9, true),
  ('picole', 'premium', 'Ninho com Abacaxi', 12.9, true),
  ('picole', 'premium', 'Ninho com Coco em Flocos', 12.9, true),
  ('picole', 'premium', 'Ninho com Morango', 12.9, true),
  ('picole', 'premium', 'Ninho Trufado', 12.9, true),
  ('picole', 'premium', 'Passas ao Rum', 12.9, true),
  ('picole', 'premium', 'Pé de Moleque', 12.9, true),
  ('picole', 'premium', 'Skimó', 12.9, true),
  ('picole', 'premium', 'Tentacao', 12.9, true),
  ('picole', 'premium', 'Torta de Limao', 12.9, true),
  ('picole', 'premium', 'Torta de Maracuja', 12.9, true),
  ('picole', 'zero_acucar', 'Abacaxi', 12.9, true),
  ('picole', 'zero_acucar', 'Acai', 12.9, true),
  ('picole', 'zero_acucar', 'Caja-Manga', 12.9, true),
  ('picole', 'zero_acucar', 'Chocolate', 12.9, true),
  ('picole', 'zero_acucar', 'Coco Branco', 12.9, true),
  ('picole', 'zero_acucar', 'Morango', 12.9, true),
  ('picole', 'zero_acucar', 'Ninho com Morango', 12.9, true),
  ('picole', 'zero_acucar', 'Ninho Trufado', 12.9, true),
  ('picole', 'zero_acucar', 'Uva', 12.9, true),
  ('picole', 'kids', 'Chiclete', 6.9, true),
  ('picole', 'kids', 'Chocolate', 6.9, true),
  ('picole', 'kids', 'Groselha', 6.9, true),
  ('picole', 'gourmet', 'Ninho com Pistache', 14.9, true),
  ('picole', 'gourmet', 'Pistache', 14.9, true),
  ('picole', 'gourmet', 'Pistache Zero Acúcar', 14.9, true),
  ('picole', 'proteica', 'Chocolate Belga', 14.9, true),
  ('picole', 'proteica', 'Cookie and Cream', 14.9, true),
  ('picole', 'proteica', 'Morango em Pedacos', 14.9, true),
  ('paleta', 'paleta', 'Acai com Leite Condensado', 21.9, true),
  ('paleta', 'paleta', 'Chocolate com trufas', 21.9, true),
  ('paleta', 'paleta', 'Coco com Trufas', 21.9, true),
  ('paleta', 'paleta', 'Maracuja com Leite Condensado', 21.9, true),
  ('paleta', 'paleta', 'Morango com Leite Condensado', 21.9, true),
  ('paleta', 'paleta', 'Ninho com Trufas', 21.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Abacaxi', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Chocolate', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Chocolate Branco', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Coco Branco', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Creme', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Flocos', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Frutas do Bosque', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Limao Suico', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Maracuja', 79.9, true),
  ('sorvete', 'tradicional_1_5_l', 'Pave Italiano', 79.9, true),
  ('sorvete', 'premium_1_5_l', 'Avela com Chocolate', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Caja-Manga', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Capuccino', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Chocomenta', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Coco Queimado', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Cookie', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Cupuacu', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Jabuticaba', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Maltine Preto', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Morango Fruta', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Ninho com Abacaxi', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Ninho com Coco em Flocos', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Ninho com Figo', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Ninho com Morango', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Ninho Trufado', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Passas ao Rum', 89.9, true),
  ('sorvete', 'premium_1_5_l', 'Pistache', 89.9, true),
  ('sorvete', 'acai_1_5_l', 'Acai Premium', 99.9, true),
  ('sorvete', 'acai_1_5_l', 'Acai com Cupuacu', 99.9, true),
  ('sorvete', 'acai_1_5_l', 'Acai com Ninho', 99.9, true),
  ('sorvete', 'acai_1_0_l', 'Acai Zero Acúcar', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Caja-Manga', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Chocolate', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Coco Branco', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Creme de Avela', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Cupuacu', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Ninho com Morango', 94.9, true),
  ('sorvete', 'zero_acucar_1_0_l', 'Ninho Trufado', 94.9, true);
