"use client";
import {useEffect,useState} from 'react';import {useParams} from 'next/navigation';import Link from 'next/link';import {supabase} from '@/lib/supabase';
const KEY='frutos_cliente';
const etapas=[{id:'recebido',titulo:'Pedido recebido',msg:'Recebemos seu pedido e ele já está na fila. 🍨'},{id:'em_preparo',titulo:'Em preparo',msg:'Estamos preparando tudo com carinho.'},{id:'saiu_para_entrega',titulo:'Saiu para entrega',msg:'Seu pedido está a caminho! 🛵'},{id:'entregue',titulo:'Entregue',msg:'Pedido concluído. Aproveite! 💚'}];
export default function Pedido(){const params=useParams();const numero=Number(params.numero);const [dados,setDados]=useState<any>(null);const [loading,setLoading]=useState(true);const [cred,setCred]=useState<any>(null);
 async function carregar(c:any){const {data}=await supabase.rpc('detalhe_pedido_cliente',{p_numero:numero,p_cpf:c.cpf,p_whatsapp:c.whatsapp});setDados(data);setLoading(false)}
 useEffect(()=>{let c:any;try{const s=localStorage.getItem(KEY);if(s)c=JSON.parse(s)}catch{}if(!c){setLoading(false);return}setCred(c);carregar(c);return},[numero]);
 useEffect(()=>{if(!dados?.pedido?.id||!cred)return;const ch=supabase.channel(`pedido-${dados.pedido.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'pedidos',filter:`id=eq.${dados.pedido.id}`},()=>carregar(cred)).subscribe();return()=>{supabase.removeChannel(ch)}},[dados?.pedido?.id,cred]);
 if(loading)return <main className="mx-auto max-w-md p-4 pb-24"><p className="text-sm text-neutral-500">Carregando pedido...</p></main>;
 if(!dados?.encontrado)return <main className="mx-auto max-w-md p-4 pb-24"><h1 className="text-xl font-bold">Pedido #{numero}</h1><p className="mt-2 text-sm text-neutral-500">Não encontramos este pedido no seu cadastro.</p><Link href="/pedidos" className="mt-4 block rounded-lg bg-brand-700 p-3 text-center text-white">Meus pedidos</Link></main>;
 const p=dados.pedido;const atual=Math.max(0,etapas.findIndex(e=>e.id===p.status_pedido));const subtotal=(dados.itens??[]).reduce((s:number,i:any)=>s+Number(i.preco_unitario)*Number(i.quantidade),0);const atualInfo=etapas[atual];
 return <main className="mx-auto max-w-md p-4 pb-24"><div className="mb-5"><Link href="/pedidos" className="text-sm text-brand-700">← Meus pedidos</Link><div className="mt-3 flex items-start justify-between"><div><p className="text-xs text-neutral-500">Acompanhamento</p><h1 className="text-2xl font-bold">Pedido #{p.numero}</h1><p className="mt-1 text-xs text-neutral-500">{new Date(p.criado_em).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold text-brand-700">{atualInfo.titulo}</span></div></div>
 <section className="mb-5 rounded-2xl border bg-white p-5"><h2 className="font-bold">{atualInfo.titulo}</h2><p className="mt-1 text-sm text-neutral-500">{atualInfo.msg}</p><div className="mt-6">{etapas.map((e,i)=>{const ok=i<=atual;const corrente=i===atual;return <div key={e.id} className="relative flex gap-3 pb-6 last:pb-0">{i<etapas.length-1&&<div className={`absolute left-[11px] top-6 h-full w-0.5 ${i<atual?'bg-brand-700':'bg-neutral-200'}`}/>}<div className={`relative z-10 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 text-[10px] font-bold ${ok?'border-brand-700 bg-brand-700 text-white':'border-neutral-300 bg-white text-neutral-400'}`}>{ok?'✓':i+1}</div><div><div className={`text-sm font-semibold ${corrente?'text-brand-700':ok?'text-neutral-900':'text-neutral-400'}`}>{e.titulo}</div>{corrente&&<div className="mt-0.5 text-xs text-neutral-500">Atualizado automaticamente</div>}</div></div>})}</div></section>
 <section className="mb-5 rounded-2xl border bg-white p-4"><h2 className="mb-3 font-semibold">Itens do pedido</h2>{(dados.itens??[]).map((i:any)=><div key={i.id} className="border-t py-3 first:border-t-0"><div className="flex justify-between gap-3"><div><span className="font-medium">{i.quantidade}x {i.produto_nome??'Produto'}</span>{i.variacao_nome&&<p className="text-xs text-neutral-500">{i.variacao_nome}</p>}{i.adicionais?.length>0&&<p className="text-xs text-neutral-500">+ {i.adicionais.map((a:any)=>a.nome).join(', ')}</p>}</div><span className="text-sm">R$ {(Number(i.preco_unitario)*Number(i.quantidade)).toFixed(2)}</span></div></div>)}</section>
 <section className="mb-5 rounded-2xl border bg-white p-4 text-sm"><div className="flex justify-between py-1"><span>Subtotal</span><span>R$ {subtotal.toFixed(2)}</span></div>{Number(p.desconto_fidelidade)>0&&<div className="flex justify-between py-1 text-green-700"><span>Desconto fidelidade</span><span>- R$ {Number(p.desconto_fidelidade).toFixed(2)}</span></div>}<div className="flex justify-between py-1"><span>Entrega</span><span>R$ {Number(p.taxa_entrega||0).toFixed(2)}</span></div><div className="mt-2 flex justify-between border-t pt-3 text-base font-bold"><span>Total</span><span>R$ {Number(p.valor_total).toFixed(2)}</span></div><div className="mt-3 border-t pt-3 text-xs text-neutral-500"><p>{p.tipo_entrega==='entrega'?`Entrega: ${p.endereco_entrega||''}`:'Retirada na loja'}</p><p className="mt-1">Pagamento: {p.forma_pagamento}</p></div></section>
 {p.status_pedido==='entregue'&&dados.fidelidade?.ativo&&<section className="mb-5 rounded-2xl bg-brand-700 p-4 text-white"><p className="text-xs opacity-80">Fidelidade</p><h2 className="mt-1 font-bold">{p.fidelidade_creditada?'Compra contabilizada ✓':'Atualizando seu saldo...'}</h2><p className="mt-1 text-sm opacity-90">Saldo atual: R$ {Number(dados.fidelidade.saldo||0).toFixed(2)} de R$ {Number(dados.fidelidade.meta||100).toFixed(2)}</p>{dados.fidelidade.cupom_disponivel&&<p className="mt-2 rounded-lg bg-white/15 p-2 text-sm font-semibold">🎉 Seu cupom de 10% está disponível!</p>}</section>}
 <Link href="/" className="block rounded-xl border bg-white p-3 text-center font-medium text-brand-700">Fazer novo pedido</Link></main>}
