"use client";
import {useEffect,useMemo,useRef,useState} from 'react';import {useRouter} from 'next/navigation';import Link from 'next/link';import {supabase} from '@/lib/supabase';import CupomPedido from '@/components/CupomPedido';
const COLUNAS=[['recebido','Novos pedidos','🔔'],['em_preparo','Em preparo','🍨'],['saiu_para_entrega','Saiu para entrega','🛵'],['entregue','Entregues','✓']] as const;
const brl=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function PainelPedidos(){const router=useRouter();const [pedidos,setPedidos]=useState<any[]>([]);const [detalhe,setDetalhe]=useState<any>(null);const [itens,setItens]=useState<any[]>([]);const [erro,setErro]=useState('');const [som,setSom]=useState(true);const ids=useRef<Set<string>|null>(null);
 async function carregar(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/admin/login');return}const {data:adm}=await supabase.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(!adm){router.replace('/admin/login');return}const {data,error}=await supabase.from('pedidos').select('*,clientes(nome,telefone,whatsapp,endereco)').order('criado_em',{ascending:false}).limit(100);if(error)setErro(error.message);else{const lista=data??[];if(ids.current&&som&&lista.some(p=>!ids.current!.has(p.id)))beep();ids.current=new Set(lista.map(p=>p.id));setPedidos(lista)}}
 function beep(){try{const A=window.AudioContext||(window as any).webkitAudioContext;const c=new A(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.08,c.currentTime);o.start();o.stop(c.currentTime+.18)}catch{}}
 useEffect(()=>{carregar();const ch=supabase.channel('painel-operacional').on('postgres_changes',{event:'*',schema:'public',table:'pedidos'},()=>carregar()).subscribe();return()=>{supabase.removeChannel(ch)}},[som]);
 async function abrir(p:any){setDetalhe(p);const {data,error}=await supabase.from('itens_pedido').select('id,quantidade,preco_unitario,produtos(nome),variacoes(nome),adicionais_ids').eq('pedido_id',p.id);if(error){setErro(error.message);return}const adIds=[...new Set((data??[]).flatMap((x:any)=>x.adicionais_ids??[]))];let ads:any[]=[];if(adIds.length){const r=await supabase.from('adicionais').select('id,nome,preco').in('id',adIds);ads=r.data??[]}setItens((data??[]).map((x:any)=>({id:x.id,quantidade:x.quantidade,preco_unitario:x.preco_unitario,produto_nome:x.produtos?.nome,variacao_nome:x.variacoes?.nome,adicionais:ads.filter(a=>(x.adicionais_ids??[]).includes(a.id))})))}
 async function mudar(p:any,status:string){const {error}=await supabase.from('pedidos').update({status_pedido:status}).eq('id',p.id);if(error)setErro(error.message);else{if(detalhe?.id===p.id)setDetalhe({...detalhe,status_pedido:status});await carregar()}}
 const hoje=useMemo(()=>pedidos.filter(p=>new Date(p.criado_em).toDateString()===new Date().toDateString()),[pedidos]);const fat=hoje.reduce((s,p)=>s+Number(p.valor_total||0),0);
 return <main className="min-h-screen bg-neutral-100"><header className="sticky top-0 z-30 border-b bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 p-4"><div><Link href="/admin" className="text-xs text-brand-700">← Admin</Link><h1 className="text-xl font-bold">Painel de pedidos</h1></div><div className="flex items-center gap-2"><button onClick={()=>setSom(!som)} className={`rounded-lg border px-3 py-2 text-xs ${som?'bg-green-50 text-green-700':''}`}>{som?'🔊 Alerta ligado':'🔇 Alerta desligado'}</button><button onClick={carregar} className="rounded-lg border px-3 py-2 text-xs">Atualizar</button></div></div><div className="mx-auto grid max-w-[1500px] grid-cols-3 gap-2 px-4 pb-3"><Kpi t="Pedidos hoje" v={hoje.length}/><Kpi t="Em andamento" v={pedidos.filter(p=>!['entregue','cancelado'].includes(p.status_pedido)).length}/><Kpi t="Total hoje" v={brl(fat)}/></div></header>{erro&&<div className="mx-auto mt-3 max-w-[1500px] rounded-lg bg-red-50 p-3 text-sm text-red-700">{erro}</div>}
 <section className="mx-auto grid max-w-[1500px] gap-4 overflow-x-auto p-4 lg:grid-cols-4">{COLUNAS.map(([status,titulo,ico])=><div key={status} className="min-w-[280px] rounded-2xl bg-neutral-200/60 p-3"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">{ico} {titulo}</h2><span className="rounded-full bg-white px-2 py-1 text-xs font-bold">{pedidos.filter(p=>p.status_pedido===status).length}</span></div><div className="space-y-3">{pedidos.filter(p=>p.status_pedido===status).map(p=><article key={p.id} className={`rounded-xl border bg-white p-4 shadow-sm ${status==='recebido'?'border-orange-300 ring-1 ring-orange-100':''}`}><div className="flex justify-between"><div><span className="text-lg font-black">#{p.numero}</span><p className="text-xs text-neutral-500">{new Date(p.criado_em).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</p></div><b>{brl(p.valor_total)}</b></div><p className="mt-3 font-semibold">{p.clientes?.nome||'Cliente'}</p><p className="text-xs text-neutral-500">{p.tipo_entrega==='entrega'?'🛵 Entrega':'🏪 Retirada'} · {p.forma_pagamento}</p><button onClick={()=>abrir(p)} className="mt-3 w-full rounded-lg border py-2 text-sm font-semibold">Ver pedido</button><div className="mt-2 flex gap-2">{status==='recebido'&&<button onClick={()=>mudar(p,'em_preparo')} className="flex-1 rounded-lg bg-brand-700 py-2 text-xs font-bold text-white">Iniciar preparo</button>}{status==='em_preparo'&&<button onClick={()=>mudar(p,'saiu_para_entrega')} className="flex-1 rounded-lg bg-brand-700 py-2 text-xs font-bold text-white">Saiu / pronto</button>}{status==='saiu_para_entrega'&&<button onClick={()=>mudar(p,'entregue')} className="flex-1 rounded-lg bg-green-700 py-2 text-xs font-bold text-white">Concluir</button>}</div></article>)}</div></div>)}</section>
 {detalhe&&<div className="fixed inset-0 z-50 flex justify-end bg-black/40" onClick={()=>setDetalhe(null)}><aside className="h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs text-neutral-500">Detalhes</p><h2 className="text-2xl font-black">Pedido #{detalhe.numero}</h2></div><button onClick={()=>setDetalhe(null)} className="text-2xl">×</button></div><div className="mt-4 rounded-xl bg-neutral-50 p-3 text-sm"><b>{detalhe.clientes?.nome}</b><p>{detalhe.clientes?.whatsapp||detalhe.clientes?.telefone}</p><p className="mt-2">{detalhe.tipo_entrega==='entrega'?detalhe.endereco_entrega||detalhe.clientes?.endereco:'Retirada na loja'}</p><p>{detalhe.forma_pagamento}</p></div><div className="mt-4">{itens.map(i=><div key={i.id} className="border-b py-3 text-sm"><div className="flex justify-between"><b>{i.quantidade}x {i.produto_nome}</b><span>{brl(Number(i.preco_unitario)*i.quantidade)}</span></div>{i.variacao_nome&&<p className="text-xs text-neutral-500">{i.variacao_nome}</p>}{i.adicionais?.length>0&&<p className="text-xs text-neutral-500">+ {i.adicionais.map((a:any)=>a.nome).join(', ')}</p>}</div>)}</div><div className="mt-4 flex justify-between border-t pt-4 text-lg font-black"><span>Total</span><span>{brl(detalhe.valor_total)}</span></div><div className="mt-5"><CupomPedido pedido={detalhe} itens={itens}/></div></aside></div>}</main>}
function Kpi({t,v}:{t:string;v:any}){return <div className="rounded-xl bg-neutral-50 p-3"><p className="text-[11px] text-neutral-500">{t}</p><b>{v}</b></div>}
