import { linkRastreamento, statusUber } from './entregas';
export type CredUber={ambiente:string;customer_id:string;client_id:string;client_secret:string;webhook_signing_key:string};
export function conferirAmbiente(c:CredUber){if(!c.customer_id||!c.client_id||!c.client_secret||!c.webhook_signing_key)throw new Error('Complete as credenciais da Uber, incluindo a chave do webhook.');if(process.env.VERCEL_ENV!=='production'&&c.ambiente!=='teste')throw new Error('O piloto aceita apenas credenciais de teste da Uber.');}
export async function tokenUber(c:CredUber){conferirAmbiente(c);const r=await fetch('https://auth.uber.com/oauth/v2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.client_id,client_secret:c.client_secret,grant_type:'client_credentials',scope:'eats.deliveries'}),cache:'no-store',signal:AbortSignal.timeout(15000)});const b=await r.json();if(!r.ok||!b.access_token)throw new Error('A Uber recusou a autenticação. Confira as credenciais e o ambiente.');return b.access_token as string;}
export async function chamarUber(c:CredUber,token:string,caminho:string,body?:unknown){const r=await fetch(`https://api.uber.com/v1/customers/${encodeURIComponent(c.customer_id)}/${caminho}`,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store',signal:AbortSignal.timeout(20000)});const b=await r.json().catch(()=>({}));return {ok:r.ok,status:r.status,body:b};}
export function resumoUber(body:any){const status=statusUber(body?.status);if(!status||typeof body?.id!=='string'||!body.id.startsWith('del_'))throw new Error('Resposta de entrega inválida da Uber.');return {id:body.id,status,tracking_url:linkRastreamento(body.tracking_url),pickup_eta:body.pickup_eta??null,dropoff_eta:body.dropoff_eta??null,courier:body.courier?{nome:String(body.courier.name??''),telefone:String(body.courier.phone_number??'')}:null,updated:body.updated??body.created};}
export function enderecoLoja(e:any){const address=[e.endereco,e.cidade&&`${e.cidade}/${e.estado??''}`,e.cep&&`CEP ${e.cep}`].filter(Boolean).join(' - ');if(!e.endereco||!e.cidade||!e.estado||!e.cep)throw new Error('Complete endereço, cidade, estado e CEP da loja.');return address;}
export async function cotarUber(db:any,c:CredUber,token:string,empresaId:string,origem:string,destino:string,pedidoId:string|null=null){
 const r=await chamarUber(c,token,'delivery_quotes',{pickup_address:origem,dropoff_address:destino});const q=r.body;
 if(!r.ok)throw new Error('A Uber não conseguiu cotar este endereço. Confira a disponibilidade e tente novamente.');
 if(typeof q.id!=='string'||!q.id.startsWith('dqt_')||!Number.isInteger(q.fee)||q.fee<0||String(q.currency).toUpperCase()!=='BRL'||!Number.isFinite(Date.parse(q.expires))||Date.parse(q.expires)<=Date.now())throw new Error('Cotação inválida ou expirada da Uber.');
 const {error}=await db.from('uber_cotacoes').insert({quote_id:q.id,empresa_id:empresaId,pedido_id:pedidoId,origem,destino,valor:q.fee/100,expira_em:q.expires,ambiente:c.ambiente,customer_id:c.customer_id});
 if(error)throw new Error('Não foi possível registrar a cotação.');
 return {quoteId:q.id,valor:q.fee/100,moeda:'BRL',expiraEm:q.expires,duracaoMinutos:Number.isFinite(Number(q.duration))?Number(q.duration):null};
}
