"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";import {useCarrinho} from "@/lib/carrinho-context";import {FormaPagamento,TipoEntrega} from "@/lib/types";import {supabase} from "@/lib/supabase";
const KEY="frutos_cliente";type Cliente={nome:string;cpf:string;whatsapp:string;endereco:string};type Fid={ativo:boolean;saldo:number;cupom_disponivel:boolean;endereco?:string};
export default function Checkout(){const router=useRouter();const{itens,subtotal,limpar}=useCarrinho();const[cliente,setCliente]=useState<Cliente|null>(null);const[tipo,setTipo]=useState<TipoEntrega>("entrega");const[endereco,setEndereco]=useState("");const[horarioRetirada,setHorarioRetirada]=useState("");const[pagamento,setPagamento]=useState<FormaPagamento>("pix");const[fid,setFid]=useState<Fid|null>(null);const[usarFid,setUsarFid]=useState(false);const[enviando,setEnviando]=useState(false);const[erro,setErro]=useState("");
useEffect(()=>{try{const s=localStorage.getItem(KEY);if(s){const c=JSON.parse(s) as Cliente;setCliente(c);setEndereco(c.endereco||"");supabase.rpc('consultar_fidelidade',{p_cpf:c.cpf,p_whatsapp:c.whatsapp}).then(({data})=>{if(data){const x=data as Fid&{encontrado?:boolean};setFid(x);if(!c.endereco&&x.endereco){const n={...c,endereco:x.endereco};setCliente(n);setEndereco(x.endereco);localStorage.setItem(KEY,JSON.stringify(n));}}})}}catch{}},[]);
const taxa=tipo==='entrega'&&endereco?6:0;const desconto=usarFid&&fid?.ativo&&fid.cupom_disponivel?subtotal*.10:0;const total=subtotal-desconto+taxa;const formas:FormaPagamento[]=tipo==='entrega'?["pix","cartao"]:["dinheiro","pix","cartao"];
function salvarEndereco(v:string){setEndereco(v);if(cliente){const c={...cliente,endereco:v};setCliente(c);localStorage.setItem(KEY,JSON.stringify(c));}}
async function confirmar(){if(!cliente){router.push('/cadastro');return}if(tipo==='entrega'&&!endereco.trim()){setErro('Informe o endereço de entrega.');return}setEnviando(true);setErro('');const r=await fetch('/api/pedidos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cliente:{nome:cliente.nome,cpf:cliente.cpf,telefone:cliente.whatsapp,whatsapp:cliente.whatsapp},tipoEntrega:tipo,endereco:tipo==='entrega'?endereco:null,horarioRetirada:tipo==='retirada'&&horarioRetirada?new Date(`${new Date().toISOString().slice(0,10)}T${horarioRetirada}:00`).toISOString():null,taxaEntrega:taxa,pagamento,itens,usarFidelidade:usarFid})});const d=await r.json();setEnviando(false);if(!r.ok){setErro(d.error||'Não foi possível criar o pedido.');return}limpar();router.push(`/pedido/${d.numero}`)}
return <main className="mx-auto max-w-md p-4 pb-24"><h1 className="mb-4 text-base font-medium">Como você quer receber?</h1>{!cliente?<Link href="/cadastro" className="mb-4 block rounded-xl border border-brand-200 bg-brand-50 p-4 text-sm font-medium text-brand-700">Cadastre-se para continuar e participar do programa de fidelidade →</Link>:<div className="mb-4 rounded-xl border bg-white p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{cliente.nome}</b><p className="text-xs text-neutral-500">{cliente.whatsapp} · CPF {cliente.cpf}</p></div><Link href="/cadastro" className="text-xs text-brand-700">Editar</Link></div></div>}
{fid?.ativo&&<div className="mb-4 rounded-xl border border-brand-100 bg-brand-50 p-3"><b className="text-sm text-brand-800">Programa de fidelidade</b><p className="mt-1 text-xs text-brand-700">Acumulado: R$ {Number(fid.saldo||0).toFixed(2)} de R$ 100,00</p>{fid.cupom_disponivel&&<label className="mt-3 flex items-center gap-2 rounded-lg bg-white p-3 text-sm font-medium"><input type="checkbox" checked={usarFid} onChange={e=>setUsarFid(e.target.checked)}/> Usar meu cupom de 10% neste pedido</label>}</div>}
<div className="mb-4 flex gap-2">{(["entrega","retirada"] as TipoEntrega[]).map(t=><button key={t} onClick={()=>setTipo(t)} className={`flex-1 rounded-lg border py-3 text-sm font-medium capitalize ${tipo===t?'border-brand-600 bg-brand-50 text-brand-700':'border-neutral-200 text-neutral-500'}`}>{t}</button>)}</div>{tipo==='entrega'?<div className="mb-4"><label className="mb-1 block text-xs text-neutral-500">Endereço de entrega</label><textarea value={endereco} onChange={e=>salvarEndereco(e.target.value)} placeholder="Rua, número, complemento e bairro" className="min-h-20 w-full rounded-lg border px-3 py-2 text-sm"/><p className="mt-1 text-xs text-neutral-400">Endereço salvo para os próximos pedidos. Você pode editar quando precisar.</p></div>:<div className="mb-4"><label className="mb-1 block text-xs text-neutral-500">Horário de retirada</label><input type="time" value={horarioRetirada} onChange={e=>setHorarioRetirada(e.target.value)} className="w-full rounded-lg border px-3 py-2 text-sm"/></div>}
<label className="mb-1 block text-xs text-neutral-500">Forma de pagamento</label><div className="mb-4 flex gap-2">{formas.map(f=><button key={f} onClick={()=>setPagamento(f)} className={`flex-1 rounded-lg border py-2 text-sm capitalize ${pagamento===f?'border-brand-600 bg-brand-50 text-brand-700':'border-neutral-200 text-neutral-500'}`}>{f}</button>)}</div><div className="border-t pt-3 text-sm"><div className="flex justify-between text-neutral-500"><span>Subtotal</span><span>R$ {subtotal.toFixed(2)}</span></div>{desconto>0&&<div className="flex justify-between text-green-700"><span>Cupom fidelidade (10%)</span><span>- R$ {desconto.toFixed(2)}</span></div>}{tipo==='entrega'&&<div className="flex justify-between text-neutral-500"><span>Taxa de entrega</span><span>R$ {taxa.toFixed(2)}</span></div>}<div className="mt-1 flex justify-between font-medium"><span>Total</span><span>R$ {total.toFixed(2)}</span></div></div>{erro&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{erro}</p>}<button onClick={confirmar} disabled={!itens.length||enviando} className="mt-4 w-full rounded-lg bg-brand-700 py-3 text-sm font-medium text-white disabled:opacity-40">{enviando?'Enviando...':'Confirmar pedido'}</button></main>}
