"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { DashboardSuperadmin } from "@/lib/superadmin";
import { Assinatura, DadosComerciais, PlanoComercial, dataSaoPaulo, resumoAssinaturas, somarDias, statusAssinatura } from "@/lib/superadmin-comercial";
import { brl } from "./Dashboard";
const field = "mt-1 w-full rounded-lg border bg-white p-2.5 text-sm disabled:opacity-60";
type PlanoForm = { id: string | null; nome: string; descricao: string; ativo: boolean; preco_mensal: string; dias_teste: number; modulos: string[]; versao: number };
type SubForm = { empresa_id: string; plano_id: string; valor_mensal: string; status: Assinatura['status']; inicio: string; fim_teste: string; vencimento: string; notas: string; versao: number };
export default function Comercial({ aba, empresas, atualizado }: { aba: "planos" | "assinaturas"; empresas: DashboardSuperadmin['empresas']; atualizado: () => Promise<void> }) {
  const [dados,setDados]=useState<DadosComerciais|null>(null),[erro,setErro]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  const [plano,setPlano]=useState<PlanoForm|null>(null),[sub,setSub]=useState<SubForm|null>(null);
  const [filtro,setFiltro]=useState("todos"),[busca,setBusca]=useState("");
  const saving=useRef(false),generation=useRef(0);
  async function request(body?:unknown) {
    const {data:{session}}=await supabase.auth.getSession(); if(!session)throw new Error("Sessão expirada. Entre novamente no Superadmin.");
    const res=await fetch("/api/superadmin/comercial",{method:body?"POST":"GET",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});
    const data=await res.json();if(!res.ok)throw new Error(data.error||"Não foi possível carregar.");return data;
  }
  const carregar=useCallback(async()=>{const token=++generation.current;setBusy(true);setErro("");try{const next=await request();if(token===generation.current)setDados(next);}catch(e){if(token===generation.current)setErro(e instanceof Error?e.message:"Erro ao carregar.");}finally{if(token===generation.current)setBusy(false);}},[]);
  useEffect(()=>{carregar();return()=>{generation.current++;};},[carregar]);
  useEffect(()=>{setPlano(null);setSub(null);setMsg("");},[aba]);
  async function salvar(e:FormEvent) {
    e.preventDefault();if(saving.current||!dados)return;saving.current=true;setBusy(true);setErro("");setMsg("");
    try {
      if(plano)await request({...plano,acao:"salvar_plano",preco_mensal:Number(plano.preco_mensal)});
      else if(sub){const p=dados.planos.find(p=>p.id===sub.plano_id);await request({...sub,acao:"salvar_assinatura",valor_mensal:Number(sub.valor_mensal),plano_versao:p?.versao});}
      setPlano(null);setSub(null);setMsg("Alteração salva e registrada no histórico.");await carregar();await atualizado();
    }catch(e){setErro(e instanceof Error?e.message:"Não foi possível salvar.");}finally{saving.current=false;setBusy(false);}
  }
  function editarPlano(p?:PlanoComercial){setSub(null);setErro("");setMsg("");setPlano(p?{...p,descricao:p.descricao||"",preco_mensal:p.preco_mensal===null?"":String(p.preco_mensal),modulos:dados!.planoModulos.filter(m=>m.plano_id===p.id&&m.ativo&&dados!.modulos.some(v=>v.id===m.modulo_id)).map(m=>m.modulo_id)}:{id:null,nome:"",descricao:"",ativo:true,preco_mensal:"",dias_teste:7,modulos:[],versao:0});}
  function editarSub(empresa_id:string){const current=dados!.assinaturas.find(s=>s.empresa_id===empresa_id);setPlano(null);setErro("");setMsg("");setSub(current?{...current,valor_mensal:String(current.valor_mensal),fim_teste:current.fim_teste||"",vencimento:current.vencimento||""}:{empresa_id,plano_id:"",valor_mensal:"",status:"trial",inicio:dataSaoPaulo(),fim_teste:"",vencimento:"",notas:"",versao:0});}
  function escolherPlano(id:string){const p=dados!.planos.find(p=>p.id===id);setSub(s=>s?{...s,plano_id:id,valor_mensal:p?.preco_mensal===null||!p?"":String(p.preco_mensal),fim_teste:p?.dias_teste?somarDias(s.inicio,p.dias_teste):""}:s);}
  function descreverRegistro(r:Record<string,unknown>){const lines:string[]=[];if(r.nome||r.nome_plano_snapshot)lines.push(String(r.nome||r.nome_plano_snapshot));if(r.preco_mensal!==undefined||r.valor_mensal!==undefined)lines.push(`Mensalidade: ${brl(Number(r.preco_mensal??r.valor_mensal))}`);if(r.dias_teste!==undefined)lines.push(`Teste: ${r.dias_teste} dias`);if(r.status)lines.push(`Status: ${statusAssinatura[r.status as Assinatura["status"]]||r.status}`);for(const [key,label] of [["inicio","Início"],["fim_teste","Fim do teste"],["vencimento","Vencimento"]])if(r[key])lines.push(`${label}: ${String(r[key]).split("-").reverse().join("/")}`);if(r.ativo!==undefined)lines.push(`Disponível: ${r.ativo?"Sim":"Não"}`);if(Array.isArray(r.modulos))lines.push(`Módulos: ${r.modulos.map(id=>dados?.modulos.find(m=>m.id===id)?.nome||"Módulo descontinuado").join(", ")||"Somente cardápio"}`);if(r.modulo_id)lines.push(`Módulo: ${dados?.modulos.find(m=>m.id===r.modulo_id)?.nome||"Módulo"}`);if(r.origem==="plano")lines.push("Usar os módulos do plano");if(r.notas)lines.push(`Observação: ${r.notas}`);return lines.join("\n");}
  if(!dados)return <section className="rounded-2xl border bg-white p-6">{busy?<p role="status">Carregando planos e assinaturas…</p>:<><p role="alert" className="text-sm text-red-700">{erro}</p><button onClick={carregar} className="mt-4 rounded-lg border p-2 text-sm">Tentar novamente</button></>}</section>;
  const resumo=resumoAssinaturas(dados.assinaturas),hoje=dataSaoPaulo();
  const visiveis=empresas.filter(e=>e.nome.toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR"))&&(filtro==="todos"||(filtro==="sem"?!dados.assinaturas.some(s=>s.empresa_id===e.id):dados.assinaturas.some(s=>s.empresa_id===e.id&&s.status===filtro))));
  return <>
    {erro&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{erro}</p>}{msg&&<p role="status" className="mb-4 rounded-xl bg-green-50 p-4 text-sm text-green-700">{msg}</p>}
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-neutral-500">{aba==="planos"?"Defina os recursos e o preço de cada plano.":"Controle manual, sem cobrança automática ou bloqueio das lojas."}</p><div className="flex gap-2"><button disabled={busy||!!plano||!!sub} onClick={carregar} className="rounded-xl border bg-white p-2.5 text-sm disabled:opacity-50">Atualizar</button>{aba==="planos"&&<button disabled={busy||!!plano} onClick={()=>editarPlano()} className="rounded-xl bg-brand-700 p-2.5 text-sm font-semibold text-white disabled:opacity-50">+ Novo plano</button>}</div></div>
    {(plano||sub)&&<section className="mb-5 rounded-2xl border border-brand-200 bg-white p-5"><h3 className="text-lg font-bold">{plano?plano.id?"Editar plano":"Novo plano":`Assinatura · ${empresas.find(e=>e.id===sub!.empresa_id)?.nome}`}</h3><form onSubmit={salvar}><fieldset disabled={busy} className="mt-4 grid gap-4 sm:grid-cols-2">
      {plano?<><label className="text-xs font-semibold">Nome<input required maxLength={100} value={plano.nome} onChange={e=>setPlano({...plano,nome:e.target.value})} className={field}/></label><label className="text-xs font-semibold">Mensalidade (R$)<input required type="number" min="0" max="999999.99" step="0.01" value={plano.preco_mensal} onChange={e=>setPlano({...plano,preco_mensal:e.target.value})} className={field}/></label><label className="text-xs font-semibold">Dias de teste<input type="number" min="0" max="365" required value={plano.dias_teste} onChange={e=>setPlano({...plano,dias_teste:Number(e.target.value)})} className={field}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={plano.ativo} onChange={e=>setPlano({...plano,ativo:e.target.checked})}/>Disponível para novas assinaturas</label><label className="text-xs font-semibold sm:col-span-2">Descrição<textarea maxLength={1000} value={plano.descricao} onChange={e=>setPlano({...plano,descricao:e.target.value})} className={field}/></label><div className="sm:col-span-2"><p className="mb-2 text-sm font-semibold">Módulos incluídos</p><div className="grid gap-2 sm:grid-cols-2">{dados.modulos.map(m=><label key={m.id} className="flex gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={plano.modulos.includes(m.id)} onChange={e=>setPlano({...plano,modulos:e.target.checked?[...plano.modulos,m.id]:plano.modulos.filter(id=>id!==m.id)})}/>{m.nome}</label>)}</div><p className="mt-3 text-xs text-amber-800">Alterar módulos afeta as empresas deste plano que não possuem exceções. Alterar o preço não modifica mensalidades já contratadas.</p></div></>:sub&&<>
      <label className="text-xs font-semibold">Plano<select required value={sub.plano_id} onChange={e=>escolherPlano(e.target.value)} className={field}><option value="">Selecione</option>{dados.planos.filter(p=>p.ativo||p.id===sub.plano_id).map(p=><option key={p.id} value={p.id}>{p.nome}{!p.ativo?" (inativo)":""}</option>)}</select></label><label className="text-xs font-semibold">Mensalidade contratada (R$)<input required type="number" min="0" max="999999.99" step="0.01" value={sub.valor_mensal} onChange={e=>setSub({...sub,valor_mensal:e.target.value})} className={field}/></label><label className="text-xs font-semibold">Status<select value={sub.status} onChange={e=>setSub({...sub,status:e.target.value as Assinatura['status']})} className={field}>{Object.entries(statusAssinatura).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs font-semibold">Início<input required type="date" value={sub.inicio} onChange={e=>setSub({...sub,inicio:e.target.value})} className={field}/></label><label className="text-xs font-semibold">Fim do teste<input required={sub.status==="trial"} type="date" min={sub.inicio} value={sub.fim_teste} onChange={e=>setSub({...sub,fim_teste:e.target.value})} className={field}/></label><label className="text-xs font-semibold">Próximo vencimento<input required={sub.status==="ativa"||sub.status==="atrasada"} type="date" min={sub.inicio} value={sub.vencimento} onChange={e=>setSub({...sub,vencimento:e.target.value})} className={field}/></label><label className="text-xs font-semibold sm:col-span-2">Observação da alteração<textarea maxLength={1000} value={sub.notas} onChange={e=>setSub({...sub,notas:e.target.value})} className={field}/></label><p className="text-xs text-amber-800 sm:col-span-2">Salvar vincula a empresa ao plano escolhido. Exceções de módulos são preservadas. Status comercial e vencimento não desativam a loja ou geram cobranças.</p>
      </>}
    </fieldset><div className="mt-5 flex gap-2"><button disabled={busy} className="rounded-xl bg-brand-700 px-5 py-2.5 text-sm text-white disabled:opacity-50">{busy?"Salvando…":"Salvar"}</button><button type="button" disabled={busy} onClick={()=>{setPlano(null);setSub(null);}} className="rounded-xl border px-4 py-2.5 text-sm">Cancelar</button></div></form></section>}
    {aba==="planos"?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dados.planos.map(p=><section key={p.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h3 className="text-lg font-bold">{p.nome}</h3><span className="text-xs text-neutral-500">{p.ativo?"Disponível":"Inativo"}</span></div><p className="mt-3 text-3xl font-bold">{p.preco_mensal===null?"A definir":brl(Number(p.preco_mensal))}<span className="text-xs font-normal text-neutral-500"> / mês</span></p><p className="mt-2 text-xs text-neutral-500">{p.dias_teste} dias de teste · {empresas.filter(e=>e.plano_id===p.id).length} empresas vinculadas</p><p className="mt-3 text-sm text-neutral-600">{p.descricao}</p><ul className="mt-4 space-y-1 text-sm">{dados.modulos.filter(m=>dados.planoModulos.some(v=>v.plano_id===p.id&&v.modulo_id===m.id&&v.ativo)).map(m=><li key={m.id}>✓ {m.nome}</li>)}</ul>{!dados.planoModulos.some(v=>v.plano_id===p.id&&v.ativo)&&<p className="mt-3 text-sm text-neutral-500">Cardápio visual, sem módulos de pedidos.</p>}<button disabled={busy||!!plano} onClick={()=>editarPlano(p)} className="mt-5 rounded-xl border px-4 py-2 text-sm disabled:opacity-50">Editar plano</button></section>)}</div>:<>
      <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Mensalidades ativas",brl(resumo.mrr)],["Assinaturas ativas",resumo.ativas],["Em teste",resumo.testes],["Pendências",resumo.pendencias]].map(([label,value])=><section key={label} className="rounded-xl border bg-white p-4"><p className="text-xs text-neutral-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></section>)}</div><p className="mb-4 text-xs text-neutral-500">Mensalidades ativas representam o valor mensal contratado, não pagamentos recebidos. Pendências incluem atraso manual e vencimentos/testes ultrapassados.</p>
      <div className="mb-4 flex flex-wrap gap-3"><label className="min-w-0 flex-1 text-xs">Empresa<input value={busca} onChange={e=>setBusca(e.target.value)} className={field}/></label><label className="text-xs">Status<select value={filtro} onChange={e=>setFiltro(e.target.value)} className={field}><option value="todos">Todos</option><option value="sem">Sem assinatura</option>{Object.entries(statusAssinatura).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
      <div className="space-y-3">{visiveis.map(e=>{const s=dados.assinaturas.find(s=>s.empresa_id===e.id);const vencido=s&&(s.status==="trial"?s.fim_teste&&s.fim_teste<hoje:s.status==="ativa"&&s.vencimento&&s.vencimento<hoje);return <section key={e.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-4"><div className="min-w-0"><h3 className="font-bold">{e.nome}</h3><p className="mt-1 text-sm text-neutral-500">{s?`${s.nome_plano_snapshot} · ${brl(Number(s.valor_mensal))}/mês · ${statusAssinatura[s.status]}`:"Sem assinatura cadastrada"}</p>{s&&<p className="mt-1 text-xs text-neutral-500">{s.status==="trial"?`Fim do teste: ${s.fim_teste}`:`Vencimento: ${s.vencimento||"—"}`}</p>}{vencido&&<p className="mt-1 text-xs text-amber-800">Data ultrapassada: revise o status manualmente.</p>}</div><button disabled={busy||!!sub} onClick={()=>editarSub(e.id)} className="rounded-lg border px-4 py-2 text-sm disabled:opacity-50">{s?"Gerenciar":"Cadastrar assinatura"}</button></section>;})}{!visiveis.length&&<p className="p-5 text-sm text-neutral-500">Nenhuma empresa encontrada.</p>}</div>
    </>}
    <section className="mt-6 rounded-2xl border bg-white p-5"><h3 className="font-bold">Histórico comercial</h3><p className="mt-1 text-xs text-neutral-500">Até 100 alterações mais recentes, com valores registrados no momento da alteração.</p><div className="mt-4 space-y-3">{dados.historico.filter(h=>aba==="planos"?h.entidade==="plano":h.entidade!=="plano").map(h=><details key={h.id} className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer">{new Date(h.criado_em).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})} · {h.entidade} · {h.empresa_id?empresas.find(e=>e.id===h.empresa_id)?.nome||"Empresa":String(h.depois?.nome||"Plano")}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["Antes",h.antes],["Depois",h.depois]].map(([label,registro])=><div key={String(label)}><p className="font-semibold">{String(label)}</p><pre className="mt-1 max-h-48 overflow-auto whitespace-pre-wrap break-all rounded bg-neutral-50 p-2 text-xs">{registro?descreverRegistro(registro as Record<string,unknown>):"Novo cadastro"}</pre></div>)}</div></details>)}{!dados.historico.length&&<p className="text-sm text-neutral-500">Ainda não há alterações registradas.</p>}</div></section>
  </>;
}

