import { DashboardSuperadmin, EmpresaSuperadmin, ModuloSuperadmin, moduloEfetivo } from "@/lib/superadmin";
export default function EmpresaDetalhes({ empresa, dados, bloqueado, editar, alternar, herdar }: {
  empresa: EmpresaSuperadmin; dados: DashboardSuperadmin; bloqueado: boolean;
  editar: () => void; alternar: (modulo: ModuloSuperadmin) => void; herdar: (modulo: ModuloSuperadmin) => void;
}) {
  const dominio = empresa.dominio_principal;
  const seguro = dominio && /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(dominio);
  return <section className="mt-5 rounded-2xl border bg-white p-5 md:p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-neutral-500">Detalhes da empresa</p><h3 className="mt-1 text-xl font-bold">{empresa.nome}</h3><p className="mt-1 text-sm text-neutral-500">{dominio || "Domínio não informado"} · {empresa.slug}</p></div><div className="flex flex-wrap gap-2"><button disabled={bloqueado} onClick={editar} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-50">Editar dados</button>{seguro && <a href={`https://${dominio}/admin`} target="_blank" rel="noopener noreferrer" className="rounded-xl border px-4 py-2 text-sm">Abrir painel ↗</a>}</div></div>
    <p className="mt-3 text-xs text-neutral-500">O painel da loja exige o acesso administrativo correspondente.</p>
    <h4 className="mt-6 border-t pt-5 font-bold">Módulos disponíveis</h4><p className="mt-1 text-xs text-neutral-500">As alterações abaixo criam uma exceção ao plano para esta empresa.</p>
    <div className="mt-4 grid gap-3 md:grid-cols-2">{dados.modulos.map(m => { const state = moduloEfetivo(empresa, m.id, dados.empresaModulos, dados.planoModulos); return <div key={m.id} className="flex items-start justify-between gap-4 rounded-xl border p-4"><div><b className="text-sm">{m.nome}</b><p className="mt-1 text-xs text-neutral-500">{m.descricao || m.chave}</p><p className="mt-2 text-xs text-neutral-500">{state.origem === "empresa" ? "Exceção da empresa" : "Herdado do plano"}</p>{state.origem === "empresa" && <button disabled={bloqueado} onClick={() => herdar(m)} className="mb-2 block text-xs font-semibold text-brand-700 disabled:opacity-50">Usar regra do plano</button>}<span className="text-xs font-semibold">{state.ativo ? "Liberado" : "Não liberado"}</span></div><button role="switch" aria-checked={state.ativo} aria-label={`${state.ativo ? "Desativar" : "Liberar"} ${m.nome}`} disabled={bloqueado} onClick={() => alternar(m)} className={`relative h-7 w-12 shrink-0 rounded-full ${state.ativo ? "bg-brand-600" : "bg-neutral-300"} disabled:opacity-50`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow ${state.ativo ? "left-6" : "left-1"}`} /></button></div>; })}{!dados.modulos.length && <p className="text-sm text-neutral-500">Nenhum módulo disponível.</p>}</div>
    <h4 className="mt-6 border-t pt-5 font-bold">Configuração das integrações</h4><p className="mt-1 text-xs text-neutral-500">O cadastro de credenciais não confirma conexão ou saúde do provedor.</p>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{([['mercado_pago', 'Mercado Pago', 'pagamento_online'], ['uber_direct', 'Uber envio', 'entrega_integrada'], ['ifood', 'iFood', 'entrega_integrada'], ['meta_whatsapp', 'WhatsApp', 'whatsapp_api']] as const).map(([provedor, nome, chave]) => {
      const cred = dados.credenciais.find(c => c.empresa_id === empresa.id && c.provedor === provedor);
      const integrado = dados.integracoes.find(i => i.empresa_id === empresa.id && i.provedor === provedor);
      const modulo = dados.modulos.find(m => m.chave === chave);
      const liberado = modulo ? moduloEfetivo(empresa, modulo.id, dados.empresaModulos, dados.planoModulos).ativo : false;
      return <div key={provedor} className="rounded-xl bg-neutral-50 p-4"><b className="text-sm">{nome}</b><p className="mt-3 text-xs font-semibold">{cred ? "Credencial cadastrada" : "Não configurado"}</p><p className="mt-1 text-xs text-neutral-500">Módulo: {liberado ? "liberado" : "não liberado"}</p><p className="mt-1 text-xs text-neutral-500">Cadastro: {integrado ? integrado.ativo ? "ativo" : "inativo" : "não informado"}</p><p className="mt-1 text-xs text-neutral-500">Ambiente: {cred ? cred.ambiente === "producao" ? "Produção" : cred.ambiente === "teste" || cred.ambiente === "sandbox" ? "Teste" : cred.ambiente : "—"}</p>{cred && <p className="mt-2 text-[11px] text-neutral-400">Atualizada em {new Date(cred.atualizado_em).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })}</p>}</div>;
    })}</div>
  </section>;
}

