"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { HorariosLoja } from "@/lib/types";

type Form = { nome:string; logo_url:string; whatsapp:string; telefone:string; endereco:string; cidade:string; estado:string; cep:string; cor_primaria:string; cor_secundaria:string; horarios:HorariosLoja };
const dias=[['segunda','Segunda'],['terca','Terça'],['quarta','Quarta'],['quinta','Quinta'],['sexta','Sexta'],['sabado','Sábado'],['domingo','Domingo']] as const;
const horariosPadrao=Object.fromEntries(dias.map(([id])=>[id,{abre:'',fecha:'',fechado:false}])) as HorariosLoja;
const vazio:Form={nome:'',logo_url:'',whatsapp:'',telefone:'',endereco:'',cidade:'',estado:'',cep:'',cor_primaria:'#15803d',cor_secundaria:'#166534',horarios:horariosPadrao};

export default function Configuracoes(){
 const router=useRouter(); const [empresaId,setEmpresaId]=useState(''); const [form,setForm]=useState<Form>(vazio); const [configOriginal,setConfigOriginal]=useState<Record<string,unknown>>({}); const [carregando,setCarregando]=useState(true); const [salvando,setSalvando]=useState(false); const [msg,setMsg]=useState(''); const [erro,setErro]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/admin/login');return}const {data:admin}=await supabase.from('admin_users').select('empresa_id').eq('user_id',user.id).maybeSingle();if(!admin?.empresa_id){setErro('Empresa do administrador não encontrada.');setCarregando(false);return}setEmpresaId(admin.empresa_id);const {data:e,error}=await supabase.from('empresas').select('nome,logo_url,whatsapp,telefone,endereco,cidade,estado,cep,cor_primaria,cor_secundaria,configuracoes').eq('id',admin.empresa_id).single();if(error||!e){setErro(error?.message||'Empresa não encontrada.');setCarregando(false);return}const cfg=(e.configuracoes&&typeof e.configuracoes==='object'?e.configuracoes:{}) as Record<string,unknown>;setConfigOriginal(cfg);const h=(cfg.horarios&&typeof cfg.horarios==='object'?cfg.horarios:{}) as HorariosLoja;setForm({nome:e.nome??'',logo_url:e.logo_url??'',whatsapp:e.whatsapp??'',telefone:e.telefone??'',endereco:e.endereco??'',cidade:e.cidade??'',estado:e.estado??'',cep:e.cep??'',cor_primaria:e.cor_primaria??'#15803d',cor_secundaria:e.cor_secundaria??'#166534',horarios:{...horariosPadrao,...h}});setCarregando(false)})()},[router]);
 function horario(d:string,c:'abre'|'fecha',v:string){setForm(f=>({...f,horarios:{...f.horarios,[d]:{...f.horarios[d],[c]:v}}}))}
 function fechado(d:string,v:boolean){setForm(f=>({...f,horarios:{...f.horarios,[d]:{...f.horarios[d],fechado:v}}}))}
 async function salvar(e:React.FormEvent){e.preventDefault();if(!empresaId)return;setSalvando(true);setErro('');setMsg('');const configuracoes={...configOriginal,horarios:form.horarios};const {error}=await supabase.from('empresas').update({nome:form.nome.trim(),logo_url:form.logo_url.trim()||null,whatsapp:form.whatsapp.trim()||null,telefone:form.telefone.trim()||null,endereco:form.endereco.trim()||null,cidade:form.cidade.trim()||null,estado:form.estado.trim()||null,cep:form.cep.trim()||null,cor_primaria:form.cor_primaria,cor_secundaria:form.cor_secundaria,configuracoes}).eq('id',empresaId);if(error)setErro(error.message);else{setConfigOriginal(configuracoes);setMsg('Configurações salvas com sucesso. Atualize a vitrine para visualizar as alterações.')}setSalvando(false)}
 if(carregando)return <main className="p-8 text-center text-sm text-neutral-500">Carregando configurações...</main>;
 return <main className="min-h-screen bg-neutral-50 text-neutral-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4"><div><h1 className="font-bold">Configurações da empresa</h1><p className="text-xs text-neutral-500">Identidade, contato e funcionamento da loja</p></div><Link href="/admin" className="rounded-lg border px-3 py-2 text-sm">← Voltar ao admin</Link></div></header><form onSubmit={salvar} className="mx-auto max-w-5xl space-y-5 p-4">{erro&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{erro}</div>}{msg&&<div className="rounded-lg bg-green-50 p-3 text-sm text-green-700">{msg}</div>}
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-semibold">Identidade da loja</h2><div className="grid gap-4 md:grid-cols-2"><Campo label="Nome da empresa" value={form.nome} onChange={v=>setForm({...form,nome:v})}/><Campo label="URL da logo" value={form.logo_url} onChange={v=>setForm({...form,logo_url:v})} placeholder="https://..."/><Cor label="Cor primária" value={form.cor_primaria} onChange={v=>setForm({...form,cor_primaria:v})}/><Cor label="Cor secundária" value={form.cor_secundaria} onChange={v=>setForm({...form,cor_secundaria:v})}/></div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-4 font-semibold">Contato e endereço</h2><div className="grid gap-4 md:grid-cols-2"><Campo label="WhatsApp" value={form.whatsapp} onChange={v=>setForm({...form,whatsapp:v})}/><Campo label="Telefone" value={form.telefone} onChange={v=>setForm({...form,telefone:v})}/><Campo label="Endereço" value={form.endereco} onChange={v=>setForm({...form,endereco:v})}/><Campo label="CEP" value={form.cep} onChange={v=>setForm({...form,cep:v})}/><Campo label="Cidade" value={form.cidade} onChange={v=>setForm({...form,cidade:v})}/><Campo label="Estado" value={form.estado} onChange={v=>setForm({...form,estado:v})}/></div></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="mb-1 font-semibold">Horário de funcionamento</h2><p className="mb-4 text-xs text-neutral-500">Defina os horários individualmente. Marque “Fechado” para dias sem atendimento.</p><div className="space-y-3">{dias.map(([id,label])=>{const h=form.horarios[id]??{};return <div key={id} className="grid items-center gap-3 rounded-lg border p-3 sm:grid-cols-[130px_1fr_1fr_110px]"><b className="text-sm">{label}</b><input type="time" disabled={!!h.fechado} value={h.abre??''} onChange={e=>horario(id,'abre',e.target.value)} className="rounded-lg border p-2 disabled:bg-neutral-100"/><input type="time" disabled={!!h.fechado} value={h.fecha??''} onChange={e=>horario(id,'fecha',e.target.value)} className="rounded-lg border p-2 disabled:bg-neutral-100"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!h.fechado} onChange={e=>fechado(id,e.target.checked)}/> Fechado</label></div>})}</div></section>
 <div className="sticky bottom-3 flex justify-end"><button disabled={salvando} className="rounded-xl bg-brand-700 px-6 py-3 font-semibold text-white shadow-lg disabled:opacity-50">{salvando?'Salvando...':'Salvar configurações'}</button></div></form></main>
}
function Campo({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-1 block text-xs font-medium text-neutral-600">{label}</span><input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border p-2.5 outline-none focus:border-brand-500"/></label>}
function Cor({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-1 block text-xs font-medium text-neutral-600">{label}</span><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-14 rounded border p-1"/><input value={value} onChange={e=>onChange(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2.5"/></div></label>}
